### ISSUE TITLE
servers error webtools version 2.3

### ISSUE THREAD

**Issue by caramelo2016** [dagalufh/WebTools.bundle#224]
Failed migrating previously installed channels.
If the error persists please restart the server.
Contact devs on the Plex forums if it occurs again.
Errorinfo:
Requested URL: /webtools2?module=git&function=getUpdateList&_=1480689488026
Error Code/Message: 500/Internal Server Error

**Comment by ukdtom** [comment]
Please upload a zip with the logs

**Comment by carlosmg2** [comment]
similar issue after migrating from 2.2 to 2.3

An error occured.
Failed updating UAS Cache. Reload the page and try again.
If the error persists please restart the server.
Contact devs on the Plex forums if it occurs again.
Errorinfo:
Requested URL: /webtools2?module=git&function=updateUASCache&_=1481201244627
Error Code/Message: 500/Internal Server Error

**Comment by ukdtom** [comment]
As already said...I need logs!

**Comment by carlosmg2** [comment]
[com.plexapp.plugins.WebTools.log.txt](https://github.com/dagalufh/WebTools.bundle/files/640198/com.plexapp.plugins.WebTools.log.txt)

**Comment by ukdtom** [comment]
Huh....Not a log file for WebTools, but more likely some contact info for you ;-)

**Comment by carlosmg2** [comment]
yeah, mistake
[com.plexapp.plugins.WebTools.log.txt](https://github.com/dagalufh/WebTools.bundle/files/640690/com.plexapp.plugins.WebTools.log.txt)

**Comment by ukdtom** [comment]
Okay....

First of all...You are having a problem with downloading and updating the UAS repro, and not migrating, which is what this GHI is about...

Secondly, you gave me the last logfile, but they roll over, so your error is not in the log ;-)

But when said...

Go to the menu, and do a reset...when it returns, do a migrate

And closing this now, since unrelated to OP of this GHI, and he did not respond

Fell free to create a new GHI if problem is not resolved with above steps

/T
