### ISSUE TITLE
UAS and counter

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#68]
On the uas page, it would be nice with a total counter, as well as an installed counter

**Comment by dagalufh** [comment]
Since i'm using your getUASTypes, i'm not going through every item on loading anymore.

Meaning:
Since you already do that inorder to list the types.
Change your returnobject to be:
[{'Type': 'Application','Installed':4,'Total':20},{'Type':'Music','Installed':2,'Total':10}]

Then i can just add that to the output. And i can just sum up those values and show the grandtotal on the All button aswell.

**Comment by ukdtom** [comment]
Fix checked in.
Req. changes in GUI as well, since Dict structure has changed

**Comment by dagalufh** [comment]
Included in next commit.
